import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogOutBtn from './LogOutBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let userInfo = await getServerSession(authOptions);
  let [mode, setMode] = useState('light')

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          <Link href='/register'>Signup</Link>
          {userInfo === null 
            ? <LoginBtn /> 
            : <>
                <LogOutBtn />
                <span> {userInfo.user.name}님, 어서오세요!</span>
              </>
          }
          <button onClick={()=>{ setMode('dark') }}>다크모드</button> 
        </div>  
        {children}
      </body>
    </html>
  )
}
